### ISSUE TITLE
Trimming first char

### ISSUE THREAD

**Issue by GlitchMonkey** [kaltinril/NameToUUID#1] opened 2015-04-15 16:42 UTC
It looks like the script is trimming off the first character in the UUID.

as an example:
 {
    "uuid": "5d1a1829-3924-f94a-0faa-0a76b3ec9db6",
    "name": "******_"
  },
  {
    "uuid": "e5d1a182-9392-4f94-a0fa-aa76b3ec9db6",
    "name": "**_****"
  }

The second one is the correct one. This was seen for all uuid -> name pairs.

**Comment by kaltinril** [comment] 2015-04-15 20:33
I've reviewed the code, run the jar file, and tested this on two different Windows 7 machines.  I've also tested it on Ubuntu 14.04 LTS edition with openjdk-7-jre.

I don't see how the program could strip out the first character because the script explicitly gets characters 0 through 18, then adds a dash.

https://github.com/kaltinril/NameToUUID/blob/master/NameToUUID/src/com/kaltinril/minecraft/nametouuid/NameToUUID.java#L91-L95

The code highlighted above is what is adding the Dashes.  by default the return from calling the minecraft API provides {"ID":"###################","name","$$$$$$$"}.  However, minecraft expects the format to be {"UUID":"######-####-####-##########","name","$$$$$$$"}.  So the highlighted code will add the required dashes.

I used the file provided in a separate communication channel, and I am unable to reproduce this issue.

**Comment by kaltinril** [comment] 2015-07-15 21:52
No further comments about this being an issue, closing it.

**Closed as completed by kaltinril** 2015-07-15 21:52 UTC
